import { Section } from '../types/agent';

export const agentSections: Section[] = [
  {
    id: 'kontakt',
    number: 1,
    name: 'KONTAKTDATEN',
    totalQuestions: 4,
    avatarMessage: 'Vollständige Kontaktdaten sind entscheidend. Recruiter müssen dich schnell erreichen können. LinkedIn zeigt Professionalität.',
    avatarStepInfo: 'Tipp: Eine professionelle E-Mail-Adresse (vorname.nachname@...) macht einen besseren Eindruck als Spitznamen.',
    questions: [
      {
        id: 'name',
        number: 1,
        question: 'Wie heißt du?',
        hint: 'Dein vollständiger Name für den CV',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'vorname', label: 'Vorname', placeholder: 'Max', required: true },
          { name: 'nachname', label: 'Nachname', placeholder: 'Mustermann', required: true },
        ],
      },
      {
        id: 'kontakt_info',
        number: 2,
        question: 'Wie können Recruiter dich erreichen?',
        hint: 'Email ist Pflicht, Telefon optional',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'email', label: 'Email', type: 'email', placeholder: 'max@email.de', required: true },
          { name: 'telefon', label: 'Telefon (optional)', type: 'tel', placeholder: '+49 123 456789', required: false },
        ],
      },
      {
        id: 'ort',
        number: 3,
        question: 'Wo wohnst du?',
        hint: 'Stadt reicht - PLZ ist optional',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'ort', label: 'Stadt', placeholder: 'München', required: true },
          { name: 'plz', label: 'PLZ (optional)', placeholder: '80331', required: false },
        ],
      },
      {
        id: 'online',
        number: 4,
        question: 'Hast du LinkedIn oder ein Portfolio?',
        hint: 'Optional, aber empfohlen',
        type: 'multi_input',
        required: false,
        fields: [
          { name: 'linkedin', label: 'LinkedIn', placeholder: 'linkedin.com/in/max-mustermann', required: false },
          { name: 'website', label: 'Website/Portfolio', placeholder: 'www.max-mustermann.de', required: false },
        ],
      },
    ],
    completionMessage: '✓ Kontaktdaten abgeschlossen!',
    nextSection: 'Bildung',
  },
  {
    id: 'bildung',
    number: 2,
    name: 'BILDUNG',
    repeatable: true,
    questionsPerEntry: 3,
    avatarMessage: 'Deine Ausbildung zeigt deine fachliche Basis. ATS-Systeme scannen nach Abschlüssen. Zeiträume und Details sind wichtig.',
    avatarStepInfo: 'Tipp: Nenne relevante Schwerpunkte und besondere Leistungen. Bei guten Noten diese unbedingt angeben!',
    questions: [
      {
        id: 'abschluss_info',
        number: 1,
        question: 'Was ist dein höchster Bildungsabschluss?',
        hint: 'Wähle deinen Abschluss aus der Liste',
        type: 'multi_input',
        required: true,
        fields: [
          {
            name: 'abschluss',
            label: 'Abschluss',
            type: 'select',
            required: true,
            options: [
              'Bachelor of Science (B.Sc.)',
              'Bachelor of Arts (B.A.)',
              'Bachelor of Engineering (B.Eng.)',
              'Master of Science (M.Sc.)',
              'Master of Arts (M.A.)',
              'Master of Engineering (M.Eng.)',
              'Master of Business Administration (MBA)',
              'Diplom',
              'Staatsexamen',
              'Promotion (Dr.)',
              'Ausbildung',
              'Abitur',
              'Fachabitur',
              'Realschulabschluss',
              'Hauptschulabschluss',
              'Sonstiges',
            ]
          },
          { name: 'institution', label: 'Uni/Schule', placeholder: 'z.B. TU München', required: true },
          { name: 'schwerpunkt', label: 'Fachrichtung (optional)', placeholder: 'z.B. Informatik, Machine Learning', required: false },
        ],
      },
      {
        id: 'zeitraum',
        number: 2,
        question: 'Von wann bis wann?',
        hint: 'Zeitraum deines Studiums/deiner Ausbildung',
        type: 'date_range',
        required: true,
        fields: [
          { name: 'von', label: 'Von', type: 'month', required: true },
          { name: 'bis', label: 'Bis', type: 'month', required: true },
        ],
      },
      {
        id: 'details',
        number: 3,
        question: 'Note oder besondere Erfolge?',
        hint: 'Optional - nur wenn relevant',
        type: 'multi_input',
        required: false,
        fields: [
          { name: 'note', label: 'Note', placeholder: 'z.B. 1.5 oder Gut', required: false },
          { name: 'beschreibung', label: 'Besonderheiten', type: 'textarea', rows: 2, placeholder: 'z.B. Stipendium, Auszeichnungen...', required: false },
        ],
      },
    ],
    addAnotherQuestion: {
      question: 'Hast du weitere Bildungsabschlüsse?',
      hint: 'z.B. vorheriger Bachelor, Ausbildung',
      showEntriesBefore: true,
      entryPreviewFormat: '{abschluss}, {institution}',
      buttons: [
        { text: 'Ja, weiteren hinzufügen', action: 'add_entry', style: 'primary' },
        { text: 'Nein, weiter zur nächsten Sektion', action: 'complete_section', style: 'secondary' },
      ],
    },
    completionMessage: '✓ Bildung abgeschlossen!',
    completionSummary: '{count} Abschlüss{plural}',
    nextSection: 'Berufserfahrung',
  },
  {
    id: 'berufserfahrung',
    number: 3,
    name: 'BERUFSERFAHRUNG',
    repeatable: true,
    questionsPerEntry: 7,
    avatarMessage: 'Konkrete Erfolge mit Zahlen überzeugen! Zeige ERGEBNISSE, nicht nur Aufgaben. Context-Felder helfen bei der Optimierung.',
    avatarStepInfo: 'Tipp: Nutze das STAR-Prinzip: Situation - Task - Action - Result. Zahlen machen deinen Impact messbar!',
    questions: [
      {
        id: 'position_firma',
        number: 1,
        question: 'Position und Unternehmen',
        hint: 'Gib deine Position und das Unternehmen an',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'position', label: 'Position', placeholder: 'z.B. Senior Product Manager', required: true },
          { name: 'firma', label: 'Unternehmen', placeholder: 'z.B. BMW AG', required: true },
          { name: 'aktuell', label: 'Ich bin aktuell noch dort', type: 'checkbox', default: false, required: false },
        ],
      },
      {
        id: 'kontext_branche',
        number: 2,
        question: 'In welcher Branche und auf welchem Level?',
        hint: 'Diese Infos helfen bei der ATS-Optimierung',
        type: 'multi_input',
        required: true,
        fields: [
          {
            name: 'industry',
            label: 'Branche',
            type: 'select',
            required: true,
            options: [
              'IT & Software',
              'Automotive',
              'Finance & Banking',
              'Healthcare & Pharma',
              'Manufacturing',
              'Retail & E-Commerce',
              'Consulting',
              'Marketing & Advertising',
              'Sales & Business Development',
              'HR & Recruiting',
              'Logistics & Supply Chain',
              'Education',
              'Public Sector',
              'Energy & Utilities',
              'Real Estate',
              'Sonstiges',
            ],
          },
          {
            name: 'roleLevel',
            label: 'Seniorität',
            type: 'select',
            required: true,
            options: [
              'Werkstudent/Praktikant',
              'Junior (0-2 Jahre)',
              'Mid-Level (2-5 Jahre)',
              'Senior (5-8 Jahre)',
              'Lead/Principal (8+ Jahre)',
              'Manager',
              'Senior Manager',
              'Head of',
              'Director',
              'VP/C-Level',
            ],
          },
        ],
      },
      {
        id: 'kontext_verantwortung',
        number: 3,
        question: 'Welche Verantwortungsbereiche hattest du?',
        hint: 'Diese Details machen deinen CV messbar und überzeugend',
        type: 'multi_input',
        required: false,
        fields: [
          { name: 'teamSize', label: 'Teamgröße (optional)', placeholder: 'z.B. 5 Mitarbeiter, Teamleitung 3 Personen', required: false },
          { name: 'budget', label: 'Budgetverantwortung (optional)', placeholder: 'z.B. 500.000€ Jahresbudget', required: false },
          { name: 'revenue', label: 'Umsatzverantwortung (optional)', placeholder: 'z.B. 2 Mio.€ Vertriebsvolumen', required: false },
        ],
      },
      {
        id: 'kontext_markt',
        number: 4,
        question: 'Welche Zielgruppe oder Märkte hast du betreut?',
        hint: 'Optional, aber hilfreich für branchenspezifische Keywords',
        type: 'text',
        placeholder: 'z.B. B2B Key Accounts DACH-Region, B2C Retail Europa, Enterprise SaaS',
        required: false,
      },
      {
        id: 'zeitraum',
        number: 5,
        question: 'Von wann bis wann?',
        hint: 'Zeitraum dieser Position',
        type: 'date_range',
        required: true,
        fields: [
          { name: 'von', label: 'Von', type: 'month', required: true },
          { name: 'bis', label: 'Bis', type: 'month', required: true, disabledIf: 'aktuell', placeholderIfDisabled: 'Heute' },
        ],
      },
      {
        id: 'aufgaben',
        number: 6,
        question: 'Was waren deine Hauptaufgaben?',
        hint: 'Beschreibe deine Kernverantwortlichkeiten',
        type: 'textarea',
        placeholder: 'z.B. Leitung von cross-funktionalen Teams, Produktstrategie, Stakeholder Management...',
        rows: 4,
        required: true,
      },
      {
        id: 'erfolge',
        number: 7,
        question: 'Was waren deine größten Erfolge?',
        hint: '🔥 WICHTIG: Nutze konkrete Zahlen und Metriken! z.B. "Steigerung um 35%", "Kostensenkung von 200k€"',
        type: 'bullet_list',
        placeholder: 'z.B. Erfolgreiche Leitung von 3 Produktlaunches mit 50% Umsatzsteigerung',
        minItems: 2,
        required: true,
        addButtonText: '+ Erfolg hinzufügen',
      },
    ],
    addAnotherQuestion: {
      question: 'Hast du weitere Berufsstationen?',
      hint: 'Vorherige Jobs die relevant sind',
      showEntriesBefore: true,
      entryPreviewFormat: '{position} bei {firma}',
      buttons: [
        { text: 'Ja, weitere hinzufügen', action: 'add_entry', style: 'primary' },
        { text: 'Nein, weiter zur nächsten Sektion', action: 'complete_section', style: 'secondary' },
      ],
    },
    completionMessage: '✓ Berufserfahrung abgeschlossen!',
    completionSummary: '{count} Position{plural}',
    nextSection: 'Skills & Kompetenzen',
  },
  {
    id: 'skills',
    number: 4,
    name: 'SKILLS & KOMPETENZEN',
    totalQuestions: 3,
    avatarMessage: 'Hard Skills müssen zur Stellenbeschreibung passen. Top 3 Skills heben deine Stärken hervor. Soft Skills zeigen deine Arbeitsweise.',
    avatarStepInfo: 'Tipp: Nenne nur Skills die du wirklich beherrschst. Im Interview werden diese oft abgefragt!',
    questions: [
      {
        id: 'hard_skills',
        number: 1,
        question: 'Welche Tools und Technologien beherrschst du?',
        hint: 'z.B. Python, Excel, Figma, SQL...',
        type: 'tag_input',
        placeholder: 'Skill eingeben und Enter drücken',
        minItems: 3,
        required: true,
      },
      {
        id: 'soft_skills',
        number: 2,
        question: 'Was sind deine stärksten Soft Skills?',
        hint: 'Wähle 3-5 aus',
        type: 'checkbox_list',
        minItems: 3,
        maxItems: 5,
        required: true,
        options: [
          { value: 'leadership', label: 'Leadership' },
          { value: 'kommunikation', label: 'Kommunikation' },
          { value: 'analytik', label: 'Analytisches Denken' },
          { value: 'problemloesung', label: 'Problemlösung' },
          { value: 'teamarbeit', label: 'Teamarbeit' },
          { value: 'zeitmanagement', label: 'Zeitmanagement' },
          { value: 'kreativitaet', label: 'Kreativität' },
          { value: 'praesentation', label: 'Präsentation' },
        ],
      },
      {
        id: 'top_skills',
        number: 3,
        question: 'Welche 3 Skills möchtest du besonders hervorheben?',
        hint: 'Diese werden prominent im CV dargestellt',
        type: 'select_from_previous',
        source: 'hard_skills',
        maxItems: 3,
        required: true,
      },
    ],
    completionMessage: '✓ Skills abgeschlossen!',
    nextSection: 'Projekte',
  },
  {
    id: 'projekte',
    number: 5,
    name: 'PROJEKTE',
    optional: true,
    repeatable: true,
    questionsPerEntry: 3,
    avatarMessage: 'Projekte demonstrieren praktische Fähigkeiten. Besonders für Einsteiger wichtig. Zeige Initiative und Umsetzungskompetenz.',
    avatarStepInfo: 'Tipp: Auch Uni-Projekte, Freelance-Arbeit oder eigene Projekte zählen. Zeige was du eigenständig umgesetzt hast!',
    introQuestion: {
      question: 'Hast du besondere Projekte?',
      hint: 'z.B. Nebenprojekte, Freelance, Uni-Projekte',
      buttons: [
        { text: 'Ja, Projekt hinzufügen', action: 'start_section', style: 'primary' },
        { text: 'Nein, überspringen', action: 'skip_section', style: 'secondary' },
      ],
    },
    questions: [
      {
        id: 'titel',
        number: 1,
        question: 'Wie heißt das Projekt?',
        type: 'text',
        placeholder: 'z.B. CRM-Implementierung',
        required: true,
      },
      {
        id: 'rolle_zeitraum',
        number: 2,
        question: 'Was war deine Rolle und der Zeitraum?',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'rolle', label: 'Rolle', placeholder: 'z.B. Projektleiter', required: true },
          { name: 'von', label: 'Von', type: 'month', required: true },
          { name: 'bis', label: 'Bis', type: 'month', required: true },
        ],
      },
      {
        id: 'beschreibung',
        number: 3,
        question: 'Beschreibe Ziel und Ergebnisse',
        hint: 'Was wolltest du erreichen? Was kam dabei raus?',
        type: 'textarea',
        rows: 4,
        placeholder: 'z.B. Ziel war Automatisierung von Vertriebsprozessen...',
        required: true,
      },
    ],
    addAnotherQuestion: {
      question: 'Weiteres Projekt hinzufügen?',
      showEntriesBefore: true,
      entryPreviewFormat: '{titel}',
      maxEntries: 3,
      buttons: [
        { text: 'Ja, weiteres Projekt', action: 'add_entry', style: 'primary' },
        { text: 'Nein, weiter', action: 'complete_section', style: 'secondary' },
      ],
    },
    completionMessage: '✓ Projekte abgeschlossen!',
    skipMessage: '⊘ Projekte übersprungen',
    completionSummary: '{count} Projekt{plural}',
    nextSection: 'Sprachen',
  },
  {
    id: 'sprachen',
    number: 6,
    name: 'SPRACHEN',
    totalQuestions: 1,
    avatarMessage: 'Sprachkenntnisse sind oft entscheidend. Gib realistische Level an - wird im Interview geprüft.',
    avatarStepInfo: 'Tipp: Verhandlungssicher bedeutet, dass du komplexe Geschäftsgespräche führen kannst. Sei ehrlich bei der Einstufung!',
    questions: [
      {
        id: 'sprachen_list',
        number: 1,
        question: 'Welche Sprachen sprichst du?',
        hint: 'Deutsch und Englisch nicht vergessen!',
        type: 'repeatable_list',
        minItems: 2,
        required: true,
        fields: [
          { name: 'sprache', label: 'Sprache', placeholder: 'z.B. Englisch', required: true },
          {
            name: 'niveau',
            label: 'Niveau',
            type: 'select',
            required: true,
            options: [
              'Muttersprache',
              'Verhandlungssicher (C2)',
              'Fließend (C1)',
              'Fortgeschritten (B2)',
              'Gute Kenntnisse (B1)',
              'Grundkenntnisse (A2)',
            ],
          },
        ],
        addButtonText: '+ Weitere Sprache',
      },
    ],
    completionMessage: '✓ Sprachen abgeschlossen!',
    nextSection: 'Zertifikate',
  },
  {
    id: 'zertifikate',
    number: 7,
    name: 'ZERTIFIKATE',
    optional: true,
    repeatable: true,
    questionsPerEntry: 2,
    avatarMessage: 'Zertifikate validieren deine Skills durch anerkannte Institutionen. Zeigen Engagement für Weiterbildung.',
    avatarStepInfo: 'Tipp: Auch nicht-technische Zertifikate wie Führerschein oder Erste-Hilfe können relevant sein!',
    introQuestion: {
      question: 'Hast du relevante Zertifikate?',
      hint: 'z.B. Scrum Master, AWS Certified, Führerschein',
      buttons: [
        { text: 'Ja, hinzufügen', action: 'start_section', style: 'primary' },
        { text: 'Nein, überspringen', action: 'skip_section', style: 'secondary' },
      ],
    },
    questions: [
      {
        id: 'titel',
        number: 1,
        question: 'Welches Zertifikat?',
        type: 'text',
        placeholder: 'z.B. Certified Scrum Master',
        required: true,
      },
      {
        id: 'details',
        number: 2,
        question: 'Von welcher Organisation?',
        type: 'multi_input',
        required: true,
        fields: [
          { name: 'organisation', label: 'Organisation', placeholder: 'z.B. Scrum Alliance', required: true },
          { name: 'datum', label: 'Erhalten am', type: 'month', required: true },
        ],
      },
    ],
    addAnotherQuestion: {
      question: 'Weiteres Zertifikat?',
      showEntriesBefore: true,
      entryPreviewFormat: '{titel}',
      buttons: [
        { text: 'Ja', action: 'add_entry', style: 'primary' },
        { text: 'Nein, weiter', action: 'complete_section', style: 'secondary' },
      ],
    },
    completionMessage: '✓ Zertifikate abgeschlossen!',
    skipMessage: '⊘ Zertifikate übersprungen',
    completionSummary: '{count} Zertifikat{plural}',
    nextSection: 'Abschluss',
  },
  {
    id: 'abschluss',
    number: 8,
    name: 'ABSCHLUSS',
    totalQuestions: 1,
    avatarMessage: 'Fast geschafft! Im nächsten Schritt kannst du optional eine Wunschstelle angeben - das steigert deine Chancen massiv.',
    avatarStepInfo: 'Tipp: Du kannst auch ohne Wunschstelle fortfahren und später verschiedene Versionen erstellen!',
    questions: [
      {
        id: 'zusaetzlich',
        number: 1,
        question: 'Noch etwas Wichtiges vergessen?',
        hint: 'z.B. Auslandsaufenthalte, Ehrenamt, Stipendien',
        type: 'textarea',
        rows: 4,
        placeholder: 'Optional - nur wenn wirklich relevant...',
        required: false,
      },
    ],
    completionMessage: 'Perfekt! Jetzt zu deiner Wunschstelle...',
    nextSection: 'Wunschstelle (optional)',
  },
];
